spring:
  application:
    name: vitramu-master

server:
  port: 5000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka